# Generated by Django 6.0.6 on 2026-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_activity_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_destinations',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='travel.destination'),
        ),
    ]
